### PR TITLE
Fix Player and Logo Display on Mobile Devices

### PR DESCRIPTION
**Pull request by nsystem1**

### CODE REVIEW

**Comment by kasperrt** [comment]
Why remove the display:none; on the mobile? The mobile website isn't suppose to have a player.

**Comment by nixolas1** [comment]
Removing display:none from the css file had no effect.

**Comment by nsystem1** [comment]
So mobile devices or devices with small screen resolution e.g windows surface can use the player. I see no reason why player shouldn't be available on mobile devices? What will happen on mobile device? What will be available?

I think our goal should be fixing mobile device player issue etc...

**Comment by kasperrt** [comment]
The webpage for mobile devices is to be used as a remote only, that is why there is an separate app being developed on the side, for this sole purpose. Mobile player won't work, because of the lockscreen. 

So, in short: 
-Mobile is for voting and adding songs.
-Desktop is for playing music, changing settings + all the functionality mobile has
-A separate app will be able to play music.

**Comment by nsystem1** [comment]
Sound Good

**Comment by kasperrt** [comment]
Yeah, had planned a link to the app, but at the moment it is just available for betatesters, and a notice that it is just a remote.

No workaround for the lockscreen, since only native code can interract with the lockscreen.

**Pull request merged**
